#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CODEX_DIR="${CODEX_HOME:-${HOME}/.codex}"
SKILL_DEST="${HOME}/.agents/skills/luna-orchestrator"
AGENT_DEST="${CODEX_DIR}/agents"
DEP_ROOT="${CODEX_DIR}/luna-orchestrator/deps"
PONYTAIL_DEST="${DEP_ROOT}/ponytail"
PONYTAIL_REPO="${LUNA_ORCH_PONYTAIL_REPO:-https://github.com/DietrichGebert/ponytail.git}"

mkdir -p "$(dirname "$SKILL_DEST")" "$AGENT_DEST" "$DEP_ROOT"

rm -rf "$SKILL_DEST"
mkdir -p "$SKILL_DEST"
cp -R "$SOURCE_DIR"/. "$SKILL_DEST"/

if [[ -n "${LUNA_ORCH_PONYTAIL_SOURCE:-}" ]]; then
  if [[ ! -f "${LUNA_ORCH_PONYTAIL_SOURCE}/skills/ponytail/SKILL.md" ]]; then
    echo "ERROR: LUNA_ORCH_PONYTAIL_SOURCE does not contain skills/ponytail/SKILL.md" >&2
    exit 1
  fi
  rm -rf "$PONYTAIL_DEST"
  mkdir -p "$PONYTAIL_DEST"
  cp -R "${LUNA_ORCH_PONYTAIL_SOURCE}"/. "$PONYTAIL_DEST"/
elif [[ ! -f "$PONYTAIL_DEST/skills/ponytail/SKILL.md" ]]; then
  if ! command -v git >/dev/null 2>&1; then
    echo "ERROR: git is required to fetch Ponytail." >&2
    echo "Install git, or set LUNA_ORCH_PONYTAIL_SOURCE to a local Ponytail checkout." >&2
    exit 1
  fi
  rm -rf "$PONYTAIL_DEST"
  echo "Fetching Ponytail dependency from $PONYTAIL_REPO ..."
  git clone --depth 1 "$PONYTAIL_REPO" "$PONYTAIL_DEST"
fi

PONYTAIL_SKILL="$PONYTAIL_DEST/skills/ponytail/SKILL.md"
[[ -f "$PONYTAIL_SKILL" ]] || { echo "ERROR: Ponytail skill not found at $PONYTAIL_SKILL" >&2; exit 1; }

mkdir -p "$SKILL_DEST/references/ponytail"
cp "$PONYTAIL_SKILL" "$SKILL_DEST/references/ponytail/SKILL.md"

rm -f "$AGENT_DEST/luna_explorer.toml"
for f in luna_reviewer.toml sol_advisor.toml astra_expert.toml; do
  cp "$SOURCE_DIR/codex-agents/$f" "$AGENT_DEST/$f"
done

cp "$SOURCE_DIR/codex-agents/luna_worker.toml" "$AGENT_DEST/luna_worker.toml"
PONYTAIL_TOML_PATH="$(printf '%s' "$PONYTAIL_SKILL" | sed 's/\\/\\\\/g; s/"/\\"/g')"
cat >> "$AGENT_DEST/luna_worker.toml" <<EOF2

# Parallel-worker-only Ponytail dependency. Generated by luna-orchestrator installer.
[[skills.config]]
path = "$PONYTAIL_TOML_PATH"
enabled = true
EOF2

if [[ -f "${HOME}/.config/ponytail/config.json" ]] && grep -Eqi '"defaultMode"[[:space:]]*:[[:space:]]*"(lite|full|ultra)"' "${HOME}/.config/ponytail/config.json"; then
  echo "WARNING: A global Ponytail configuration appears active."
  echo "         Strict v6.5 independence expects reviewers/advisors to remain Ponytail-free."
fi

if command -v claude >/dev/null 2>&1; then
  echo "Claude Code detected: $(command -v claude)"
  if claude auth status >/dev/null 2>&1; then
    echo "Claude Code authentication: available (Opus review/panel enabled in auto mode)"
  else
    echo "Claude Code authentication: not currently usable; Luna reviewer fallback will remain available"
  fi
else
  echo "Claude Code not detected; Luna reviewer fallback will be used until claude is installed/authenticated"
fi

if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
  echo "WARNING: ANTHROPIC_API_KEY is set. Claude Code may use API-billed authentication."
fi

printf '%s\n' \
  "Installed Luna Orchestrator v6.5 to: $SKILL_DEST" \
  "Installed custom agents to: $AGENT_DEST" \
  "Installed private Ponytail dependency to: $PONYTAIL_DEST" \
  "Primary Ponytail reference: $SKILL_DEST/references/ponytail/SKILL.md" \
  "Claude helpers: $SKILL_DEST/scripts/claude-job.sh, claude-review.sh, and claude-panel.sh" \
  "Removed obsolete explorer if present: luna_explorer" \
  "Fully restart Codex Desktop and start a new session." \
  "Recommended Primary: GPT-5.6 Luna / Max / Fast" \
  'Invoke with: $luna-orchestrator'
